### ISSUE TITLE
Adding `proxy-url` to kubeconfigs gets lost

### ISSUE THREAD

**Issue by particledecay** [particledecay/kconf#39]
When adding the `proxy-url` property to any cluster object in the kubeconfig, that property is removed from the kubeconfig whenever performing any "write" operations on the kubeconfig (including the `use` command).

```bash
$ grep proxy-url ~/.kube/config
    proxy-url: socks5://my-socks-server:1080
$ kconf use some-other-cluster
Using context 'some-other-cluster'
$ grep proxy-url ~/.kube/config

```

**Comment by scottnemes** [comment]
Are you able to reproduce this with the current version? Seems to work okay:

`scottn@host:~/git/kconf$ kconf use development1-developer
using context 'development1-developer'
scottn@host:~/git/kconf$ grep proxy-url ~/.kube/config
    proxy-url: socks5://my-socks-server:1080
scottn@host:~/git/kconf$ kconf use development2-developer
using context 'development2-developer'
scottn@host:~/git/kconf$ grep proxy-url ~/.kube/config
    proxy-url: socks5://my-socks-server:1080
`

**Comment by particledecay** [comment]
Yep. If I take say, the minikube default config and add it twice (so I'll get a minikube and minikube-1), I can reproduce this in the following way:

  1. `kconf use minikube`
  2. Edit the `~/.kube/config` file, find the `cluster` object for `minikube-1` and add `proxy-url: socks5://my-socks-server:1080` as a new line within that object:
  
```
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    proxy-url: socks5://my-socks-server:1080
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube-1
```
  3. `kconf use minikube-1`
  4. `proxy-url` is no longer there.

**Comment by scottnemes** [comment]
Still can't reproduce it. Using this config as the base (what I'm adding twice):
`apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: developer
  name: minikube
current-context: ""
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
`
Then starting with an empty `~/.kube/config`, following your steps. I still end up with proxy-url remaining on minikube-1.

End result is this in `~/.kube/config`:
`apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    proxy-url: socks5://my-socks-server:1080
    server: https://192.168.49.2:8443
  name: minikube-1
contexts:
- context:
    cluster: minikube
    user: developer
  name: minikube
- context:
    cluster: minikube-1
    user: developer-1
  name: minikube-1
current-context: minikube-1
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: developer-1
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
`

Can you try it with these inputs and see if it works? And either way, can you post the full input config that you are adding twice?

**Comment by particledecay** [comment]
I can repro locally. Here's the full config (using yours), before I do anything:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    proxy-url: socks5://my-socks-server:1080
    server: https://192.168.49.2:8443
  name: minikube-1
contexts:
- context:
    cluster: minikube
    user: developer
  name: minikube
- context:
    cluster: minikube-1
    user: developer-1
  name: minikube-1
current-context: minikube
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: developer-1
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
```

Here's the `~/.kube/config` file after I run `kconf use minikube`:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube
- cluster:
    certificate-authority: /home/joelinux/.minikube/ca.crt
    extensions:
    - extension:
        last-update: Thu, 16 Nov 2023 09:14:53 EST
        provider: minikube.sigs.k8s.io
        version: v1.32.0
      name: cluster_info
    server: https://192.168.49.2:8443
  name: minikube-1
contexts:
- context:
    cluster: minikube
    user: developer
  name: minikube
- context:
    cluster: minikube-1
    user: developer-1
  name: minikube-1
current-context: minikube
kind: Config
preferences: {}
users:
- name: developer
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
- name: developer-1
  user:
    client-certificate: fake-cert-file
    client-key: fake-key-file
```
