### ISSUE TITLE
Unable to add interactiveMode to user exec block

### ISSUE THREAD

**Issue by zonywhoop** [particledecay/kconf#55]
I'm using 1Password to store my kube config tokens and pulling them using a user: exec: block.  This works but `interactiveMode` is required.  When I add the `interactiveMode: Never` into the config then run `kconf use context` it removes this from the config for ALL contexts and thus fails to work. If I go back and add it into the config and use kubectl then that works just fine but the next time I run `kconf use ...` it then removes all of them again.

Example:
```yaml
- name: context1
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1
      args:
      - read
      - op://Vault/kubeconf/context1
      command: /usr/local/bin/op
      env: null
      interactiveMode: Never
```
